export interface FormData {
    personalInfo: string,
    namePlaceholder: string,
    contactPlaceholder: string,
    levelsQuestion: string,
    rowDimensions: string,
    lengthPlaceholder: string,
    widthPlaceholder: string,
    totalChickens: string,
    chickensPlaceholder: string,
    salaries: string,
    salaryPlaceholder: string,
    shedType: string,
    semiControlled: string,
    batterySheds: string,
    floor: string,
    cageType: string,
    karachiCages: string,
    faisalabadCages: string,
}